board/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qualityboard.urls')),
    path('accounts/', include('allauth.urls'))
]

qualityboard/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "qualityboard"

urlpatterns = [
    path('', views.dialpad,name="landingpage"),
    path('dp', views.index,name="index"),
    path('dpm', views.dpm,name="dpm"),
    path('mob', views.mob,name="mob"),
    path('custom', views.custom,name="custom"),
    path('eda', views.eda,name="eda"),
    path('dialpad', views.dialpad,name="dialpad"),
    path('talk', views.talk,name="talk"),
    path('contactcenter', views.contactcenter,name="contactcenter"),
    path('integration', views.integration,name="integration"),
    path('dpmcfd', views.dpmcfd,name="dpmcfd"),
    path('mobcfd', views.mobcfd,name="mobcfd"),
    path('login',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),

]

qualityboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,logout,login
from django.contrib import messages
from requests.auth import HTTPBasicAuth
from .models import DP, DPExternal, DPM, DPMExternal, ImpactAreas, ImpactApplications, EDACurrentMonth, EDAPreviousMonth, EDALearnings, CFD, IFD, CFDDPM,CFDMOB
from .form import DPForm, DPExternalForm, DPM, DPMExternal,MOB,MOBExternal,ImpactAreaForm, ImpactApplicationForm, EDAPreviousMonthForm, EDACurrentMonthForm, EDALearningsForm, CFDForm, IFDForm


import sys
from operator import itemgetter
import requests
import json
from datetime import datetime, date, timedelta
import datetime, calendar
from collections import OrderedDict
from pytz import timezone
import time
import pandas as pd
import numpy as np
import re

import os
import environ
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(SECRET_KEY = str,)
environ.Env.read_env(os.path.join(BASE_DIR,'.env'))

import warnings
warnings.filterwarnings("ignore")


def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('qualityboard:login'))

    elif ('dialpad.com' not in request.user.email):
        print("Not A Dialpad User:", request.user)
        logout(request)
        return render(request, 'login.html', {
            "message": "Invalid User Permission !!!"
        })

    else:
        dp = DP.objects.get(id=1)
        dpexternal = DPExternal.objects.get(id=1)
        dpm = DPM.objects.get(id=1)
        dpmexternal = DPMExternal.objects.get(id=1)

        lastupdatedon = dp.LastUpdate

        dpdailyjira = [dp.One,dp.Two,dp.Three,dp.Four,dp.Five,dp.Six,dp.Seven,dp.Eight,dp.Nine,dp.Ten,dp.Eleven,dp.Twelve,dp.Thirteen,dp.Fourteen, \
                       dp.Fifteen,dp.Sixteen,dp.Seventeen,dp.Eighteen,dp.Nineteen,dp.Twenty,dp.Twentyone,dp.Twentytwo,dp.Twentythree,dp.Twentyfour, \
                       dp.Twentyfive,dp.Twentysix,dp.Twentyseven,dp.Twentyeight,dp.Twentynine,dp.Thirty,dp.Thirtyone,\
                       ]
        totaldpdailyjira = list(map(int, dpdailyjira))

        dpdailysealteam = {
            'AccountBilling': int(dp.AccountBilling), 'Analytics': int(dp.Analytics), 'BackendInfrastructure': int(dp.BackendInfrastructure), 'CallExperience': int(dp.CallExperience), 'CallingFeatures': int(dp.CallingFeatures), \
            'ContactCenter': int(dp.ContactCenter), 'CustomerAgentAssist': int(dp.CustomerAgentAssist), 'DataInsights': int(dp.DataInsights), 'DeveloperPlatform': int(dp.DeveloperPlatform), 'Devices': int(dp.Devices), 'DialpadTalk': int(dp.DialpadTalk), \
            'DigitalExperience': int(dp.DigitalExperience), 'EngineeringProductivity': int(dp.EngineeringProductivity), 'FrontendInfrastructure': int(dp.FrontendInfrastructure), 'Growth': int(dp.Growth), 'Integrations': int(dp.Integrations), \
            'Messaging': int(dp.Messaging), 'Mobile': int(dp.Mobile), 'ProductionSupport': int(dp.ProductionSupport), 'UberConference': int(dp.UberConference), 'VoiceIntelligence': int(dp.VoiceIntelligence), 'Website': int(dp.Website), \
           }
        internaltop5sealteam = dict(sorted(dpdailysealteam.items(), key = itemgetter(1), reverse = True)[:5])

        dpdailystatus = {
            'Backlog': int(dp.Backlog), 'Blocked': int(dp.Blocked), 'CodeReview': int(dp.CodeReview), 'Closed': int(dp.Closed), 'InProgress': int(dp.InProgress), \
            'NeedsTriage': int(dp.NeedsTriage), 'Open': int(dp.Open), 'ReadyforTesting': int(dp.ReadyforTesting), 'ReadyforProduction': int(dp.ReadyforProduction), 'ToDo': int(dp.ToDo),
            }
        internaltop5status = dict(sorted(dpdailystatus.items(), key=itemgetter(1), reverse=True)[:5])

        dpexternaldailyjira = [dpexternal.One, dpexternal.Two, dpexternal.Three, dpexternal.Four, dpexternal.Five, dpexternal.Six, dpexternal.Seven, dpexternal.Eight, dpexternal.Nine, dpexternal.Ten, dpexternal.Eleven,
                       dpexternal.Twelve, dpexternal.Thirteen, dpexternal.Fourteen, \
                       dpexternal.Fifteen, dpexternal.Sixteen, dpexternal.Seventeen, dpexternal.Eighteen, dpexternal.Nineteen, dpexternal.Twenty, dpexternal.Twentyone,
                       dpexternal.Twentytwo, dpexternal.Twentythree, dpexternal.Twentyfour, \
                       dpexternal.Twentyfive, dpexternal.Twentysix, dpexternal.Twentyseven, dpexternal.Twentyeight, dpexternal.Twentynine, dpexternal.Thirty, dpexternal.Thirtyone, \
                       ]
        totaldpexternaldailyjira = list(map(int, dpexternaldailyjira))
        dpexternaldailysealteam = {
            'AccountBilling': int(dpexternal.AccountBilling), 'Analytics': int(dpexternal.Analytics),'BackendInfrastructure': int(dpexternal.BackendInfrastructure), 'CallExperience': int(dpexternal.CallExperience), 'CallingFeatures': int(dpexternal.CallingFeatures), \
            'ContactCenter': int(dpexternal.ContactCenter), 'CustomerAgentAssist': int(dpexternal.CustomerAgentAssist), 'DataInsights': int(dpexternal.DataInsights), 'DeveloperPlatform': int(dpexternal.DeveloperPlatform), 'Devices': int(dpexternal.Devices), 'DialpadTalk': int(dpexternal.DialpadTalk), \
            'DigitalExperience': int(dpexternal.DigitalExperience), 'EngineeringProductivity': int(dpexternal.EngineeringProductivity), 'FrontendInfrastructure': int(dpexternal.FrontendInfrastructure), 'Growth': int(dpexternal.Growth), 'Integrations': int(dpexternal.Integrations), \
            'Messaging': int(dpexternal.Messaging), 'Mobile': int(dpexternal.Mobile), 'ProductionSupport': int(dpexternal.ProductionSupport), 'UberConference': int(dpexternal.UberConference), 'VoiceIntelligence': int(dpexternal.VoiceIntelligence), 'Website': int(dpexternal.Website), \
            }
        externaltop5sealteam = dict(sorted(dpexternaldailysealteam.items(), key=itemgetter(1), reverse=True)[:5])

        dpexternaldailystatus = {
            'Backlog': int(dpexternal.Backlog), 'Blocked': int(dpexternal.Blocked), 'CodeReview': int(dpexternal.CodeReview), 'Closed': int(dpexternal.Closed), 'InProgress': int(dpexternal.InProgress), \
            'NeedsTriage': int(dpexternal.NeedsTriage), 'Open': int(dpexternal.Open), 'ReadyforTesting': int(dpexternal.ReadyforTesting), 'ReadyforProduction': int(dpexternal.ReadyforProduction), 'ToDo': int(dpexternal.ToDo),
        }
        externaltop5status = dict(sorted(dpexternaldailystatus.items(), key=itemgetter(1), reverse=True)[:5])

        return render(request,'index.html', {
            "lastupdatedon": lastupdatedon,
            "dpdailyjira": dpdailyjira,
            "dpexternaldailyjira": dpexternaldailyjira,
            "internaltop5sealteamkeys": list(internaltop5sealteam.keys()),
            "internaltop5sealteamvalues": list(internaltop5sealteam.values()),
            "internaltop5statuskeys":list(internaltop5status.keys()),
            "internaltop5statusvalues": list(internaltop5status.values()),
            "externaltop5sealteamkeys": list(externaltop5sealteam.keys()),
            "externaltop5sealteamvalues": list(externaltop5sealteam.values()),
            "externaltop5statuskeys": list(externaltop5status.keys()),
            "externaltop5statusvalues": list(externaltop5status.values()),
            "totaldpdailyjira": sum(totaldpdailyjira),
            "totaldpexternaldailyjira": sum(totaldpexternaldailyjira),
            })



def dpm(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('qualityboard:login'))

    else:
        dpm = DPM.objects.get(id=1)
        dpmexternal = DPMExternal.objects.get(id=1)

        lastdpmupdatedon = dpm.LastUpdate
        dpmdailyjira = [dpm.One, dpm.Two, dpm.Three, dpm.Four, dpm.Five, dpm.Six, dpm.Seven, dpm.Eight, dpm.Nine, dpm.Ten, dpm.Eleven, dpm.Twelve, dpm.Thirteen, dpm.Fourteen, \
                       dpm.Fifteen, dpm.Sixteen, dpm.Seventeen, dpm.Eighteen, dpm.Nineteen, dpm.Twenty, dpm.Twentyone, dpm.Twentytwo, dpm.Twentythree, dpm.Twentyfour, \
                       dpm.Twentyfive, dpm.Twentysix, dpm.Twentyseven, dpm.Twentyeight, dpm.Twentynine, dpm.Thirty, dpm.Thirtyone, \
                       ]
        totaldpmdailyjira = list(map(int, dpmdailyjira))

        dpmdailystatus = {
            'Backlog': int(dpm.Backlog), 'Blocked': int(dpm.Blocked), 'CodeReview': int(dpm.CodeReview), 'Closed': int(dpm.Closed), 'InProgress': int(dpm.InProgress), \
            'NeedsTriage': int(dpm.NeedsTriage), 'Open': int(dpm.Open), 'ReadyforTesting': int(dpm.ReadyforTesting), 'ReadyforProduction': int(dpm.ReadyforProduction), 'ToDo': int(dpm.ToDo),
        }
        internaltop5dpmstatus = dict(sorted(dpmdailystatus.items(), key=itemgetter(1), reverse=True)[:5])

        dpmexternaldailyjira = [dpmexternal.One, dpmexternal.Two, dpmexternal.Three, dpmexternal.Four, dpmexternal.Five, dpmexternal.Six, dpmexternal.Seven, dpmexternal.Eight, dpmexternal.Nine, dpmexternal.Ten, \
                               dpmexternal.Eleven, dpmexternal.Twelve, dpmexternal.Thirteen, dpmexternal.Fourteen, dpmexternal.Fifteen, dpmexternal.Sixteen, dpmexternal.Seventeen, dpmexternal.Eighteen, \
                               dpmexternal.Nineteen, dpmexternal.Twenty, dpmexternal.Twentyone, dpmexternal.Twentytwo, dpmexternal.Twentythree, dpmexternal.Twentyfour, \
                               dpmexternal.Twentyfive, dpmexternal.Twentysix, dpmexternal.Twentyseven, dpmexternal.Twentyeight, dpmexternal.Twentynine, dpmexternal.Thirty, dpmexternal.Thirtyone, \
                               ]
        totaldpmexternaldailyjira = list(map(int, dpmexternaldailyjira))

        dpmexternaldailystatus = {
            'Backlog': int(dpmexternal.Backlog), 'Blocked': int(dpmexternal.Blocked), 'CodeReview': int(dpmexternal.CodeReview), 'Closed': int(dpmexternal.Closed), 'InProgress': int(dpmexternal.InProgress), \

qualityboard/templates/baselayout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!--script src="https://cdn.jsdelivr.net/npm/chart.js"></script-->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script-->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script-->

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <!--script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.1.0/dist/chartjs-plugin-datalabels.min.js"></script-->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


    <title>Quality Board</title>
    <meta http-equiv="refresh" content="600">



  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #6f42c1;">
  <div class="container-fluid" >
    <a class="navbar-brand" href="#"><h3>Dialpad Products Health Monitoring Dashboard</h3></a>

    <div class="collapse navbar-collapse d-flex flex-row-reverse bd-highlight" id="navbarNavAltMarkup" >
      <div class="navbar-nav" >
        <!--a class="nav-link" aria-current="page" href="{% url 'qualityboard:index' %}"><h5>DP</h5></a-->
        <!--a class="nav-link" aria-current="page" href="{% url 'qualityboard:dpm' %}"><h5>DPM</h5></a-->
        <!--a class="nav-link" aria-current="page" href="{% url 'qualityboard:mob' %}"><h5>MOB</h5></a-->
        <!--a class="nav-link" aria-current="page" href="{% url 'qualityboard:custom' %}"><h5>CUSTOM</h5></a-->
        <!--a class="nav-link me-2" aria-current="page" href="{% url 'qualityboard:eda' %}"><h5>EDA</h5></a-->
        <a id="dialpad" class="nav-link" aria-current="page" href="{% url 'qualityboard:dialpad' %}"><h5>DIALPAD</h5></a>
        <a class="nav-link" aria-current="page" href="{% url 'qualityboard:dpmcfd' %}"><h5>MEETINGS</h5></a>
        <a class="nav-link" aria-current="page" href="{% url 'qualityboard:mobcfd' %}"><h5>MOBILE</h5></a>
        <a class="nav-link" aria-current="page" href="{% url 'qualityboard:custom' %}"><h5>CUSTOM</h5></a>
        <a href="{% url 'qualityboard:logout' %}">
        <button class="btn btn-light" type="submit"><h5>Logout</h5></button></a>
      </div>
    </div>
  </div>
</nav>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->

   {% block body %}

   {% endblock body %}



  </body>
</html>

qualityboard/templates/contactcenter.html
{% extends "baselayout.html" %}
{% block body %}

<div class="container-fluid" style="position: relative">

      <div class="row">
        <div class="col pt-1 fst-italic" align="left">
        <h4> Top 3 Seal Teams: <a href="{% url 'qualityboard:talk' %}">Talk |</a> <a href="{% url 'qualityboard:contactcenter' %}" style="text-decoration: underline;font-size:18px;">ContactCenter |</a> <a href="{% url 'qualityboard:integration' %}">Integration</a></h4>
        </div>
        <div class="col pt-1 fst-italic" align="right">
            **Last Updated On: {{lastupdatedon}}
        </div>
      </div>
</div>

<div class="container-fluid" >
    <div class="row" >
        <div class="col-6" style="width:80spx;height:50spx">
           <canvas id="CFDDialpadOverall" ></canvas>
        </div>
        <div class="col-6" style="width:80spx;height:50spx">
           <canvas id="CFDDialpadOverallMRT" ></canvas>
        </div>
     </div>
</div>


<div class="container-fluid" >
    <div class="row" >
        <div class="col-6" style="width:80spx;height:50spx">
           <canvas id="IFDDialpadOverall" ></canvas>
        </div>
        <div class="col-6" style="width:80spx;height:50spx">
           <canvas id="IFDDialpadOverallMRT" ></canvas>
        </div>
     </div>
</div>


<script>
const ctxone = document.getElementById('CFDDialpadOverall').getContext('2d');
const CFDDialpadOverall = new Chart(ctxone, {
    type: 'bar',
    data: {
        labels: ['Last11Months','Last3Months','LastMonth','CurrentMonth'],
        datasets: [{
            label: 'Monthly Average Count',
            data: [{% for jira in CCJiras_CFD %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',

            ],
            borderColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',

            ],
            borderWidth: 1
        }]
    },
     options: {

     scales: {
		xAxes: [{
			stacked: true,
		}],
        yAxes: [{
            stacked: true,
        }]
      },

     plugins: {
            datalabels: {
                  formatter: function(value, context) {
                  return context.chart.data.datasets[0].data[context.dataIndex];
                }
            }
          },
      legend: { display: true },

      title: {
        display: true,
        text: 'External Jiras - Contact Center'
      }

    }

});

</script>

<script>
const ctxtwo = document.getElementById('CFDDialpadOverallMRT').getContext('2d');
const CFDDialpadOverallMRT = new Chart(ctxtwo, {
    type: 'bar',
    data: {
        labels: ['Last11Months','Last3Months','LastMonth','CurrentMonth'],
        datasets: [{
            label: 'High %age',
            data: [{% for jira in CFDCCPriorityHigh %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',

            ],
            borderColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',

            ],
            borderWidth: 1
        },
        {
            label: 'Medium %age',
            data: [{% for jira in CFDCCPriorityMedium %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
            ],
            borderColor: [
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
            ],
            borderWidth: 1

        },
        {
            label: 'Low %age',
            data: [{% for jira in CFDCCPriorityLow %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
            ],
            borderWidth: 1

        },
        {
            label: 'Urgent %age',
            data: [{% for jira in CFDCCPriorityUrgent %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1)',
            ],
            borderColor: [
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(75, 192, 192, 1))',
            ],
            borderWidth: 1

        }]
    },
     options: {

     scales: {
		xAxes: [{
			stacked: true,
		}],
        yAxes: [{
            stacked: true,
        }]
      },

      legend: { display: true },

      title: {
        display: true,
        text: 'External ContactCenter Jiras - Priority (in %age)'
      }

    }

});
</script>



<script>
const ctxthree = document.getElementById('IFDDialpadOverall').getContext('2d');
const IFDDialpadOverall = new Chart(ctxthree, {
    type: 'bar',
    data: {
        labels: ['Last11Months','Last3Months','LastMonth','CurrentMonth'],
        datasets: [{
            label: 'Fixed %age',
            data: [{% for jira in CCFixed_CFD %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',

            ],
            borderColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
            ],
            borderWidth: 1

        },
        {
            label: 'Backlog %age',
            data: [{% for jira in CCBackLog_CFD %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
            ],
            borderColor: [
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(255, 206, 86, 1)',
            ],
            borderWidth: 1

        },
        {
            label: 'Noise %age',
            data: [{% for jira in CCNoise_CFD %}{{jira}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(255, 99, 132, 1)',
            ],
            borderWidth: 1

        }]
    },
     options: {

     scales: {
		xAxes: [{
			stacked: true,
		}],
        yAxes: [{
            stacked: true,
        }]
      },

     plugins: {
            datalabels: {
                  formatter: function(value, context) {
                  return context.chart.data.datasets[0].data[context.dataIndex];
                }
            }
          },
      legend: { display: true },

      title: {
        display: true,
        text: 'External Reported Jiras - Contact Center (in %age)'
      }

    }

});

</script>

<script>
const ctxfour = document.getElementById('IFDDialpadOverallMRT').getContext('2d');
const IFDDialpadOverallMRT = new Chart(ctxfour, {
    type: 'bar',
    data: {
        labels: ['Last11Months','Last3Months','LastMonth','CurrentMonth'],
        datasets: [{
            label: 'MTTR',
            data: [{% for mrt in CCMRT_CFD %}{{mrt}},{% endfor %}],
            fill: false,
            backgroundColor: [
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',

            ],
            borderColor: [
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(153, 102, 255, 1)',

            ],
            borderWidth: 1

        }]
    },
     options: {
      scales: {
		xAxes: [{
			stacked: true,
		}],
        yAxes: [{
            stacked: true,
        }]
      },
      plugins: {
            datalabels: {
                  formatter: function(value, context) {
                  return context.chart.data.datasets[0].data[context.dataIndex];
                }
            }
          },

      legend: { display: true },

      title: {
        display: true,
        {% if deltasign == 1 %}
        text: 'External Jiras - Mean Time To Resolve (in Days)'
        {%endif%}
        {% if deltasign == 0 %}
        text: 'External Jiras - Mean Time To Resolve (in Days)'
        {%endif%}
      }

    }

});

</script>

{% endblock body %}